// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreguntarOllama(arg1, arg2) {
  return window['go']['ia']['IAOllama']['PreguntarOllama'](arg1, arg2);
}
