// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ia} from '../models';

export function PreguntarOllama(arg1:string,arg2:string):Promise<ia.SnippetState>;
