// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AbrirCarpetaEnExplorador(arg1:string):Promise<void>;

export function EscribirArchivo(arg1:string,arg2:string):Promise<void>;

export function LeerArchivo(arg1:string):Promise<string>;

export function SeleccionarYLeerCarpeta():Promise<main.ResultadoCarpeta>;

export function SetContext(arg1:context.Context):Promise<void>;
