// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirCarpetaEnExplorador(arg1) {
  return window['go']['main']['AdministradorArchivos']['AbrirCarpetaEnExplorador'](arg1);
}

export function AgregarSnippet(arg1, arg2) {
  return window['go']['main']['AdministradorArchivos']['AgregarSnippet'](arg1, arg2);
}

export function EliminarArchivo(arg1) {
  return window['go']['main']['AdministradorArchivos']['EliminarArchivo'](arg1);
}

export function EscribirArchivo(arg1, arg2) {
  return window['go']['main']['AdministradorArchivos']['EscribirArchivo'](arg1, arg2);
}

export function GetVSCodePath() {
  return window['go']['main']['AdministradorArchivos']['GetVSCodePath']();
}

export function LeerArchivo(arg1) {
  return window['go']['main']['AdministradorArchivos']['LeerArchivo'](arg1);
}

export function LoadLastDirectory() {
  return window['go']['main']['AdministradorArchivos']['LoadLastDirectory']();
}

export function SeleccionarYLeerCarpeta(arg1) {
  return window['go']['main']['AdministradorArchivos']['SeleccionarYLeerCarpeta'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['AdministradorArchivos']['SetContext'](arg1);
}

export function UnirRutas(arg1) {
  return window['go']['main']['AdministradorArchivos']['UnirRutas'](arg1);
}
