// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirCarpetaEnExplorador(arg1) {
  return window['go']['main']['AdministradorArchivos']['AbrirCarpetaEnExplorador'](arg1);
}

export function EscribirArchivo(arg1, arg2) {
  return window['go']['main']['AdministradorArchivos']['EscribirArchivo'](arg1, arg2);
}

export function LeerArchivo(arg1) {
  return window['go']['main']['AdministradorArchivos']['LeerArchivo'](arg1);
}

export function SeleccionarYLeerCarpeta() {
  return window['go']['main']['AdministradorArchivos']['SeleccionarYLeerCarpeta']();
}

export function SetContext(arg1) {
  return window['go']['main']['AdministradorArchivos']['SetContext'](arg1);
}

export function UnirRutas(arg1) {
  return window['go']['main']['AdministradorArchivos']['UnirRutas'](arg1);
}
