// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AbrirCarpetaEnExplorador(arg1:string):Promise<void>;

export function AgregarSnippet(arg1:string,arg2:string):Promise<void>;

export function EliminarArchivo(arg1:string):Promise<void>;

export function EscribirArchivo(arg1:string,arg2:string):Promise<void>;

export function GetVSCodePath():Promise<string>;

export function LeerArchivo(arg1:string):Promise<string>;

export function LoadLastDirectory():Promise<string>;

export function SeleccionarYLeerCarpeta(arg1:string):Promise<main.ResultadoCarpeta>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UnirRutas(arg1:Array<string>):Promise<string>;
